title: Thi Tham Ta (Annie)
logo: IMG_9304.png
description: Ph.D. Researcher in Economics
<a href="ta-thi-tham@strath.ac.uk">Email</a>
<a href="https://www.linkedin.com/in/thi-tham-ta-349236192/">View My LinkedIn Profile</a>
#show_downloads: true
theme: jekyll-theme-minimal
